--CREATE DATABASE TELEFON_OPERATORU_SISTEMI;
--USE TELEFON_OPERATORU_SISTEMI;
CREATE TABLE MESLEK(
	MESLEK_ID INT PRIMARY KEY IDENTITY(1,1),
	AD VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE ABONE(
	TC_KIMLIK_NO CHAR(11) PRIMARY KEY CHECK (TC_KIMLIK_NO LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]') ,
	AD VARCHAR(57) NOT NULL,
	SOYAD VARCHAR(30) NOT NULL,
	DOGUM_TARIHI DATE NOT NULL,
	YAS AS DATEDIFF(yy,DOGUM_TARIHI,GETDATE()),
	MESLEK_ID INT FOREIGN KEY REFERENCES  MESLEK(MESLEK_ID) 
);

CREATE TABLE BANKA(
	BANKA_ID INT PRIMARY KEY IDENTITY(1,1),
	BANKA_ADI VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE TELEFON (
    TELEFON_NO CHAR(11) CONSTRAINT chkTel CHECK (TELEFON_NO LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]') PRIMARY KEY, 
    DURUM BIT NOT NULL DEFAULT 0,
	TC_KIMLIK_NO CHAR(11) FOREIGN KEY REFERENCES  ABONE(TC_KIMLIK_NO)
);
CREATE TABLE ABONELIK_SOZLESMESI(
	SOZLESME_NUMARASI INT PRIMARY KEY IDENTITY(1,1),
	BASLANGIC_TARIHI DATE DEFAULT GETDATE(),
	BITIS_TARIHI DATE NOT NULL,
	IPTAL_TARIHI DATE,
	CAYMA_BEDELI FLOAT DEFAULT 0 NOT NULL,
	FATURA_UST_SINIRI FLOAT NOT NULL,
	FATURA_ID INT FOREIGN KEY REFERENCES  MESLEK(MESLEK_ID),
	TC_KIMLIK_NO CHAR(11) FOREIGN KEY REFERENCES  ABONE(TC_KIMLIK_NO),
	TELEFON_NO CHAR(11) FOREIGN KEY REFERENCES  TELEFON(TELEFON_NO),
	BANKA_ID INT FOREIGN KEY REFERENCES  BANKA(BANKA_ID)
);

CREATE TABLE BASVURU_TURU(
	BASVURU_ID INT PRIMARY KEY IDENTITY(1,1),
	BASVURU_TIPI BIT NOT NULL
);
CREATE TABLE BASVURU_SEKLI(
	BASVURU_SEKLI_ID INT PRIMARY KEY IDENTITY(1,1),
	BASVURU_SEKLI BIT NOT NULL
);

CREATE TABLE TARIFELER(
	ISIM VARCHAR(100) UNIQUE NOT NULL,
	TARIFE INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	SMS_MIKTARI INT,
	BASVURU_YASI TINYINT NOT NULL,
	INTERNET_MIKTARI INT,
	KONUSMA_MIKTARI INT,
	YENI_ABONELER_ICIN_YILLIK FLOAT,
	YENI_ABONELER_ICIN_AYLIK FLOAT,
	ESKI_ABONELER_ICIN_YILLIK FLOAT,
	ESKI_ABONELER_ICIN_AYLIK FLOAT,
	ILK_TARIH DATE,
	SON_TARIH DATE,
	ACIKLAMA TEXT,
	SOZLESME_NUMARASI INT FOREIGN KEY REFERENCES  ABONELIK_SOZLESMESI(SOZLESME_NUMARASI),
	BASVURU_ID INT FOREIGN KEY REFERENCES  BASVURU_TURU(BASVURU_ID),
	BASVURU_SEKLI_ID INT FOREIGN KEY REFERENCES  BASVURU_SEKLI(BASVURU_SEKLI_ID)
);

CREATE TABLE SOZLESME_PAKETI(
	TOTAL_DK INT,
	TOTAL_SMS INT,
	TOTAL_INTERNET INT,
	KULLANILAN_DK INT,
	KULLANILAN_SMS INT,
	KULLANILAN_INTERNET INT,
	FIYAT INT,
	BITIS_TARIHI DATE,
	BASLANGIC_TARIHI DATE NOT NULL DEFAULT GETDATE(),
	PAKET_ID INT PRIMARY KEY IDENTITY(1,1),
	YENILENME_TARIHI DATE,
	TARIFE_ID INT FOREIGN KEY REFERENCES  TARIFELER(TARIFE)
);
CREATE TABLE SIM_KARTI(
	SERI_NUMARASI INT PRIMARY KEY IDENTITY(1,1),
	PUK_KODU CHAR(4) UNIQUE,
	DURUM BIT NOT NULL,
	PÝN_KODU CHAR(4),
	SOZLESME_NUMARASI INT FOREIGN KEY REFERENCES  ABONELIK_SOZLESMESI(SOZLESME_NUMARASI),
	TELEFON_NO CHAR(11) FOREIGN KEY REFERENCES  TELEFON(TELEFON_NO)
);

CREATE TABLE SMS (
    SMS_ID INT PRIMARY KEY IDENTITY(1,1),
    KULLANILAN_SMS INT,
    GONDERME_TARIHI DATE NOT NULL DEFAULT GETDATE(),
    ALINMA_TARIHI DATE,
    MESAJ_ICERIGI TEXT,
	TELEFON_NO_ALAN CHAR(11) FOREIGN KEY REFERENCES  TELEFON(TELEFON_NO),
	TELEFON_NO_GONDEREN CHAR(11) FOREIGN KEY REFERENCES  TELEFON(TELEFON_NO),
	PAKET_ID INT FOREIGN KEY REFERENCES  SOZLESME_PAKETI(PAKET_ID)
);

CREATE TABLE DK (
    DK_ID INT PRIMARY KEY IDENTITY(1,1),
    KULLANILAN_DK INT,
    BASLANGIC_SAATI DATETIME,
    BITIS_SAATI DATETIME,
    KONUSMA_SURESI AS DATEDIFF(MINUTE,BASLANGIC_SAATI,BITIS_SAATI), 
	TELEFON_NO_ARAYAN CHAR(11) FOREIGN KEY REFERENCES  TELEFON(TELEFON_NO),
	TELEFON_NO_ARANAN CHAR(11) FOREIGN KEY REFERENCES  TELEFON(TELEFON_NO),
	PAKET_ID INT FOREIGN KEY REFERENCES  SOZLESME_PAKETI(PAKET_ID)
);

CREATE TABLE INTERNET (
    INTERNET_ID INT PRIMARY KEY IDENTITY(1,1),
    KULLANILAN_BYTE INT,
    BASLANGIC_TARIHI DATE,
    BITIS_TARIHI DATE,
	PAKET_ID INT FOREIGN KEY REFERENCES  SOZLESME_PAKETI(PAKET_ID)
);

CREATE TABLE ODEME_KANALI (
    ODEME_KANALI_ID INT PRIMARY KEY IDENTITY(1,1),
    AD VARCHAR(20),
);

CREATE TABLE FATURA (
    FATURA_ID INT PRIMARY KEY IDENTITY(1,1),
    FATURA_TUTARI FLOAT,
    FATURA_KESIM_TARIHI DATE,
    FATURA_BASLANGIC_TARIHI DATE,
    FATURA_BITIS_TARIHI DATE,
    SON_ODEME_BASLANGIC_TARIHI DATE,
    SON_ODEME_BITIS_TARIHI DATE,
    ODENME_TARIHI DATE,
	TC_KIMLIK_NO CHAR(11) FOREIGN KEY REFERENCES  ABONE(TC_KIMLIK_NO),
	SOZLESME_NUMARASI INT FOREIGN KEY REFERENCES  ABONELIK_SOZLESMESI(SOZLESME_NUMARASI),
	ODEME_KANALI_ID INT FOREIGN KEY REFERENCES  ODEME_KANALI(ODEME_KANALI_ID)
);

CREATE TABLE IL (
	IL_ID INT PRIMARY KEY IDENTITY(1,1),
	AD VARCHAR (20) NOT NULL UNIQUE
);

CREATE TABLE ILCE (
	ILCE_ID INT PRIMARY KEY IDENTITY(1,1),
	AD VARCHAR(20) NOT NULL,
	IL_ID INT FOREIGN KEY REFERENCES  IL(IL_ID),
);

CREATE TABLE MAHALLE (
	MAHALLE_ID INT PRIMARY KEY IDENTITY(1,1),
	AD VARCHAR(20) NOT NULL,
	ILCE_ID INT FOREIGN KEY REFERENCES  ILCE(ILCE_ID),

);

CREATE TABLE CADDE_SOKAK (
	CADDE_SOKAK_ID INT PRIMARY KEY IDENTITY(1,1),
	AD VARCHAR(20) NOT NULL,
	MAHALLE_ID INT FOREIGN KEY REFERENCES  MAHALLE(MAHALLE_ID)
);

CREATE TABLE ADRES (
	ADRES_ID INT PRIMARY KEY IDENTITY(1,1),
	DIS_KAPI_NO INT NOT NULL,
	IC_KAPI_NO INT NOT NULL,
	ACIKLAMA TEXT,
	TC_KIMLIK_NO CHAR(11) FOREIGN KEY REFERENCES  ABONE(TC_KIMLIK_NO),
	IL_ID INT FOREIGN KEY REFERENCES  IL(IL_ID),
	ILCE_ID INT FOREIGN KEY REFERENCES  ILCE(ILCE_ID),
	MAHALLE_ID INT FOREIGN KEY REFERENCES  MAHALLE(MAHALLE_ID),
	CADDE_SOKAK_ID INT FOREIGN KEY REFERENCES  CADDE_SOKAK(CADDE_SOKAK_ID)
);


CREATE TABLE ABONELIKSOZLESMESI_SOZLESMEPAKETI(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	SOZLESME_NUMARASI INT FOREIGN KEY REFERENCES ABONELIK_SOZLESMESI(SOZLESME_NUMARASI),
	PAKET_ID INT FOREIGN KEY REFERENCES SOZLESME_PAKETI(PAKET_ID)
);