-- 1.Sorgu
WITH Aylik_SMS AS (
    SELECT 
        A.TC_KIMLIK_NO,
        AVG(S.KULLANILAN_SMS) AS Ortalama_SMS_Gecen_Yil
    FROM 
        ABONE A
        JOIN SMS S ON A.TC_KIMLIK_NO = S.TELEFON_NO_GONDEREN
    WHERE 
        S.GONDERME_TARIHI BETWEEN DATEADD(YEAR, -1, GETDATE()) AND GETDATE()
    GROUP BY 
        A.TC_KIMLIK_NO
),
Guncel_Ay_SMS AS (
    SELECT 
        A.TC_KIMLIK_NO,
        SUM(S.KULLANILAN_SMS) AS Toplam_SMS_Bu_Ay
    FROM 
        ABONE A
        JOIN SMS S ON A.TC_KIMLIK_NO = S.TELEFON_NO_GONDEREN
    WHERE 
        S.GONDERME_TARIHI BETWEEN DATEADD(MONTH, -1, GETDATE()) AND GETDATE()
    GROUP BY 
        A.TC_KIMLIK_NO
)
SELECT 
    T.ISIM,
    COUNT(DISTINCT S.TC_KIMLIK_NO) AS Abone_Sayisi
FROM 
    TARIFELER T
    JOIN ABONELIK_SOZLESMESI S ON T.SOZLESME_NUMARASI = S.SOZLESME_NUMARASI
    JOIN ABONE A ON S.TC_KIMLIK_NO = A.TC_KIMLIK_NO
    JOIN Aylik_SMS AS A_SMS ON A.TC_KIMLIK_NO = A_SMS.TC_KIMLIK_NO
    JOIN Guncel_Ay_SMS AS G_A_SMS ON A.TC_KIMLIK_NO = G_A_SMS.TC_KIMLIK_NO
WHERE 
    G_A_SMS.Toplam_SMS_Bu_Ay > A_SMS.Ortalama_SMS_Gecen_Yil
    AND DATEDIFF(YEAR, A.DOGUM_TARIHI, GETDATE()) BETWEEN (DATEDIFF(YEAR, A.DOGUM_TARIHI, GETDATE()) - 3) AND (DATEDIFF(YEAR, A.DOGUM_TARIHI, GETDATE()) + 3)
GROUP BY 
    T.ISIM
HAVING 
    COUNT(DISTINCT S.TC_KIMLIK_NO) >= 1000
ORDER BY 
    Abone_Sayisi DESC;



-- 2.Sorgu
SELECT 
    T.ISIM AS TARIFE_ADI,
    COUNT(DISTINCT A.TC_KIMLIK_NO) AS TOPLAM_AKTIF_ABONE_SAYISI,
    COUNT(DISTINCT CASE WHEN IL.AD = 'Yalova' THEN A.TC_KIMLIK_NO END) AS YALOVA_AKTIF_ABONE_SAYISI,
    COUNT(DISTINCT CASE WHEN DATEDIFF(YEAR, A.DOGUM_TARIHI, GETDATE()) < 30 THEN A.TC_KIMLIK_NO END) AS YAS_ALTI_30_AKTIF_ABONE_SAYISI
FROM 
    TARIFELER T
    JOIN SOZLESME_PAKETI SP ON T.TARIFE = SP.TARIFE_ID
    JOIN ABONELIKSOZLESMESI_SOZLESMEPAKETI ASP ON SP.PAKET_ID = ASP.PAKET_ID
    JOIN ABONELIK_SOZLESMESI ASZ ON ASP.SOZLESME_NUMARASI = ASZ.SOZLESME_NUMARASI
    JOIN ABONE A ON ASZ.TC_KIMLIK_NO = A.TC_KIMLIK_NO
    LEFT JOIN ADRES ADR ON A.TC_KIMLIK_NO = ADR.TC_KIMLIK_NO
    LEFT JOIN IL IL ON ADR.IL_ID = IL.IL_ID
WHERE 
    ASZ.IPTAL_TARIHI IS NULL
GROUP BY 
    T.ISIM
ORDER BY 
    TOPLAM_AKTIF_ABONE_SAYISI DESC, 
    YALOVA_AKTIF_ABONE_SAYISI DESC, 
    YAS_ALTI_30_AKTIF_ABONE_SAYISI DESC;